# Config for doordash-specific stuff
source ~/.doordash_config

# Config for different git operations
source ~/.git_config


# homebrew config
eval "$(/opt/homebrew/bin/brew shellenv)"

# command line shortcuts
alias k=kubectl

# warpify terminal
printf '\eP$f{"hook": "SourcedRcFileForWarp", "value": { "shell": "zsh" }}\x9c'

# premium jetbrains 
export PATH="/Applications/IntelliJ IDEA.app/Contents/MacOS:$PATH"
export PATH="/Applications/PyCharm.app/Contents/MacOS:$PATH"

# community edition jetbrains (commented out for company work)
# export PATH="/Applications/IntelliJ IDEA CE.app/Contents/MacOS:$PATH"
# export PATH="/Applications/PyCharm CE.app/Contents/MacOS:$PATH"

export LDFLAGS="-L$(brew --prefix zlib)/lib -L$(brew --prefix openssl)/lib"
export CPPFLAGS="-I$(brew --prefix zlib)/include -I$(brew --prefix openssl)/include"
export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix openssl)/lib/pkgconfig"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/justin.lieb/.sdkman"
[[ -s "/Users/justin.lieb/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/justin.lieb/.sdkman/bin/sdkman-init.sh"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
