source ~/.bash_profile
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/justin.lieb/.sdkman"
[[ -s "/Users/justin.lieb/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/justin.lieb/.sdkman/bin/sdkman-init.sh"
